language: python
sudo: false
python:
- '2.7'
addons:
  postgresql: "9.4"

before_script:
- export DATABASE_URL=postgres://postgres@localhost/workshop
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c "CREATE DATABASE workshop;" -U postgres

install:
  - pip install ansible
  - pip install -r requirements/development.txt

script:
- flake8
- py.test --cov -v --tb=native

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
