# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid_upload_path.storage
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_event', models.CharField(max_length=256)),
                ('photo_of_the_area', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to)),
                ('description_of_the_event', models.CharField(help_text='Description of the Event', max_length=100)),
                ('location', models.CharField(max_length=256)),
                ('name_of_the_contact_person', models.CharField(max_length=256)),
                ('phone_number_of_the_contact_person', models.CharField(help_text='Phone Number of the Contact Person', max_length=100)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-name_of_the_event'],
            },
        ),
    ]
