# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_of_the_event',
            field=models.CharField(blank=True, help_text='Duration in days', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='timings',
            field=models.CharField(blank=True, help_text='Timing of the event', max_length=1000),
        ),
    ]
